apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 10.0.2.15
  