apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
  labels:
    role: nginx
spec:
  volumes:
    - name: nginx-data
      hostPath:
        path: /home/ubuntu/07hostpath
        type: DirectoryOrCreate # 디렉토리가 없으면 생성함
  containers:
    - name: nginx
      image: nginx
      command: ["bash","-c",
                "while true; do echo 'Hello, World!!' >> /nginx_data/hello.txt; sleep 3; done"]
      ports:
        - name: nginx
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /nginx_data
          name: nginx-data