apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    app: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # 하나의 노드에서만 읽기/쓰기 가능
  persistentVolumeReclaimPolicy: Retain # 볼륨 해제에도 데이터 보존
  storageClassName: local-storage
  local:
    path: /home/ubuntu/08pv
  nodeAffinity: # 로컬 볼륨이 특정 노드에 종속적이기 때문에 추가 필요
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - microk8s
  